name: Vanish
main: erkam2002\Vanish
version: 2.0.0
author: erkam2002
api: 3.0.0-ALPHA6
commands:
  vanish:
    description: "Vanish your self"
    aliases: [Vanish]
permissions:
  vanish.use:
    description: "Vanish use perm"
    default: op
