name: SuperVanish
main: erkam2002\Vanish
version: 2.0
author: erkam2002
api: 3.0.0-ALPHA8
commands:
  supervanish:
    description: "Vanish your self"
    aliases: [sv]
permissions:
  supervanish.spectate:
    description: "Vanish use perm"
    default: op
